// Generated by Wrangler on Sun May 12 2024 22:57:06 GMT-0600 (Central Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  DB: D1Database;
}
